### ISSUE TITLE
New feature to access element childs

### ISSUE THREAD

**Issue by dbarjs** [noibe/villa#2]
Need support to access the childs of elements at next version of villa:

``` css
.child-width-100 > * {
    width: 100%;
}

.child-grow-1 > * {
    -webkit-flex-grow: 1;
    flex-grow: 1;
}
```
